name: Build and Push Docker image to AWS ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cosmo-router
          IMAGE_TAG: latest
        run: |
          docker build -t public.ecr.aws/g9o2v6t2/:$IMAGE_TAG .
          docker push public.ecr.aws/g9o2v6t2/:$IMAGE_TAG
      - name: Cleanup
        run: docker rmi public.ecr.aws/g9o2v6t2/:$IMAGE_TAG
